name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        volumes:
          - ./db/:/docker-entrypoint-initdb.d
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -d

    - name: Test
      run: go test ./... -v
